### ISSUE TITLE
Dumping nothing

### ISSUE THREAD

**Issue by ravage84** [dereuromark/cakephp-translate#10]
When I navigate to /admin/translate/translate-strings/dump, I can press the submit button even though I have no locale file under ``src\Locale/ + {locale}`` yet.

This leads to an MySQL error:

````
Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translate_project_id' cannot be null

If you are using SQL keywords as table column names, you can enable identifier quoting for your database connection in config/app.php.

SQL Query:

INSERT INTO translate_domains (name, translate_project_id, created, modified) VALUES (:c0, :c1, :c2, :c3)
````

**Comment by ravage84** [comment]
The processing script should catch this situation.

**Comment by dereuromark** [comment]
Any fix here?

**Comment by ravage84** [comment]
As I/we ended up not using the plugin, I currently have no time/focus on this. 🙇

**Comment by dereuromark** [comment]
Fixed.
