### ISSUE TITLE
Extracting leads to MySQL Error

### ISSUE THREAD

**Issue by ravage84** [dereuromark/cakephp-translate#11]
When I navigate to /admin/translate/translate-strings/extract, select both available POT files (cake, default) and rpess submit, it shows me a MySQL error:

````
Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translate_project_id' cannot be null

SQL Query:

INSERT INTO translate_domains (name, translate_project_id, created, modified) VALUES (:c0, :c1, :c2, :c3)
````

I had no way of choosing a project, though I have added one in the DB beforehand.

**Comment by dereuromark** [comment]
It should use the default one currently in selection.

**Comment by ravage84** [comment]
I thought I had one project as default. It even shows me the green tick under default int he project index and detail view. But that's not correct. In the DB i have it set to ``0``.

**Comment by ravage84** [comment]
After setting the one translation project I have to default = 1 and status = 1, I get another MySQL error:

````
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'references, translate_domain_id, active, is_html, created, modified) VALUES ('xyz' at line 1

SQL Query:

INSERT INTO translate_strings (name, references, translate_domain_id, active, is_html, created, modified) VALUES (:c0, :c1, :c2, :c3, :c4, :c5, :c6)
````

**Comment by ravage84** [comment]
The issue was with ``references`` being a reserved MySQL keyword:

https://dev.mysql.com/doc/refman/5.7/en/keywords.html

Identifier quoting resolves the problem.

The real fix was to rename the field to some unresreved term.
