### ISSUE TITLE
Use Locale instead of ISO2

### ISSUE THREAD

**Issue by ravage84** [dereuromark/cakephp-translate#13]
(Theoretically) it is possible to have more than one locale per language.

For example one could have three locales for the German language (de):

1. ``de_DE`` for German from Germany
2. ``de_CH`` for German from Switzerland
3. ``de_DE`` for German from Austria

The current implementation uses the ISO2 language code to process, extract and dump data.

Also, if one uses the full locale string as locale folder (de_CH) name instead of just the language ISO2 (de), he will end up with two locale folders.

**Comment by dereuromark** [comment]
We should fix this before I tag a first 0.1 release.

**Comment by dereuromark** [comment]
@ravage84 
I started the Cake5 upgrade

are you still interested in this plugin and should be combine forces getting it production ready?

**Comment by ravage84** [comment]
I'm not since we aren't using CakePHP 5.x yet and I never came around using this plugin,. Sorry.

**Comment by dereuromark** [comment]
This should be fixed on 5.x now.

**Comment by dereuromark** [comment]
![Image](https://github.com/user-attachments/assets/04bff59f-d9c3-4795-b0da-31e8e495824a)

in 5.x this is now defaulting to locale usage, language and iso2 code is only used for flag display :)
