### ISSUE TITLE
 Element file "Tools.Element\pagination.ctp" is missing.

### ISSUE THREAD

**Issue by DinoSane** [dereuromark/cakephp-translate#14]
Following installation by letter.

At the "Project Index" (/admin/translate/translate-projects)

I get only the 
 Element file "Tools.Element\pagination.ctp" is missing.

I'm not sure about which additional information would be useful.
PHP : 5.6.25
Cakephp: 3.4.8

**Comment by dereuromark** [comment]
Either we make it require (https://github.com/dereuromark/cakephp-translate/blob/master/composer.json#L23 ) or we include its own pagination ctp
Are you able to make a PR here?

**Comment by DinoSane** [comment]
Sorry for newbiest question ever: what is a PR :(

**Comment by dereuromark** [comment]
Pulled request

**Comment by dereuromark** [comment]
Tools plugin is alread required. Please make sure you also loaded it.
