### ISSUE TITLE
mysql error - table reserved words

### ISSUE THREAD

**Issue by mickeyze** [dereuromark/cakephp-translate#15]
Hello Dereuromark, 

I need to report a issue regarding mysql error which occurs due to usage of mysql reserved words as a column name. Simply, I'm not able to create a project, my query fails:

```
INSERT INTO translate_projects (
  name, type, default, status, created, 
  modified
) 
VALUES 
  (
    'test', 0, 0, 2, '2017-08-16 12:15:30', 
    '2017-08-16 12:15:30'
  )
```

because usage of words "type", "default", "status" as column name is not allowed and recommended by mysql. Please find list of all reserved words on mysql webpage: https://dev.mysql.com/doc/refman/5.5/en/keywords.html and https://stackoverflow.com/questions/23446377/syntax-error-due-to-using-a-reserved-word-as-a-table-or-column-name-in-mysql

UPDATE: mysql version:
mysql>  SHOW VARIABLES LIKE "%version%";
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| innodb_version          | 5.7.19                  |
| protocol_version        | 10                      |
| slave_type_conversions  |                         |
| tls_version             | TLSv1,TLSv1.1           |
| version                 | 5.7.19-0ubuntu0.16.04.1 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | Linux                   |
+-------------------------+-------------------------+
8 rows in set (0,01 sec)

Cheers, 
Miralem
![error](https://user-images.githubusercontent.com/2063771/29362991-69dca358-828e-11e7-90ca-fd5a7e21719a.png)

**Comment by dereuromark** [comment]
Please see https://github.com/dereuromark/cakephp-translate/tree/master/docs#important-database-config
