### ISSUE TITLE
CakePHP Translate isnt finding POT/PO Files in src/Locale

### ISSUE THREAD

**Issue by ahmedbodi** [dereuromark/cakephp-translate#17]
As subject

**Comment by dereuromark** [comment]
How do they look like, any specific naming? they should be able to be detected.

**Comment by ahmedbodi** [comment]
No errors, When doing the import terms it isnt finding the PO Files. When debugging, it appears as though the folder.read(true, true) is returning 2 null arrays for folder and files. The files are there and cakephp are able to use them.

**Comment by dereuromark** [comment]
Maybe the path is wrong, or permissions issues dont allow cake folder class to read them?

**Comment by ahmedbodi** [comment]
checked it all. The path was correct. As were permissions

**Comment by dereuromark** [comment]
Any idea what happened in your case?
