### ISSUE TITLE
MySQL Syntax Error when creating Translate Project

### ISSUE THREAD

**Issue by ravage84** [dereuromark/cakephp-translate#5]
> Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'default, status, created, modified) VALUES ('my-app', 0, 1, 1, '2017-05-19 ' at line 1 

> INSERT INTO translate_projects (name, type, default, status, created, modified) VALUES (:c0, :c1, :c2, :c3, :c4, :c5)

Ways to reproduce:

0. CakePHP 3.4.x app setup with PHP 5.6, MySQL 5.7.12
1. [Setup as written in README](https://github.com/dereuromark/cakephp-translate#installation)
2. [Navigate to adm/translate as written in README](https://github.com/dereuromark/cakephp-translate#usage)
3. Click Please create a project first: **Project Index**
4. Click **New Translate Project**
5. Fill out form and submit

**Comment by dereuromark** [comment]
Do you know what fields are causing it? Seems like there is one field null and schema is not nullable or sth?

**Comment by ravage84** [comment]
Not yet, name is the only field that has no default but is NOT NULLable.

**Comment by dereuromark** [comment]
'2017-05-19 ' is there a space after the date? Maybe that kills MYSQL 5.7?

**Comment by ravage84** [comment]
Could be. We have set up our dev machines rather stricl when it comes to MySQL settings (better crash on dev than on production 😼 ).

**Comment by dereuromark** [comment]
The default keyword probably, identifier quoting.
