### ISSUE TITLE
Translate Shell shows no sub commands

### ISSUE THREAD

**Issue by ravage84** [dereuromark/cakephp-translate#8]
When I run

````
myapp>bin\cake.bat translate
````

It shows:
````
Usage:
cake translate.translate [subcommand] [-h] [-q] [-v]

Subcommands:

help  Display some help.

To see help on a subcommand use `cake translate.translate [subcommand] --help`

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.
````

What sub commands can I use?

**Comment by dereuromark** [comment]
It does not ship with any, currently all happens via backend in web, would be nice to add those commands here. especially for larger projects/translations via CLI would not have any runtime timeout issues :)
But the web has the advantage of doing things directly per click in the backend for whoever has the role access.
It is a trade off of usability I guess.

**Comment by ravage84** [comment]
OK, I see.

SO, I guess you should not display the shell under https://github.com/dereuromark/cakephp-translate#usage then.

**Comment by dereuromark** [comment]
Or you can help making it useful :)
